Construction/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Diary.urls')),
    path('customer/', include('Customer.urls', namespace='customer')),

]

Customer/urls.py
from django.urls import path

from Customer.views import *

app_name = 'customer'

urlpatterns = [
    path('index', Index, name='index'),
    path('register_customer', Register_customer, name='register_customer'),
    path('list_customer', List_customer, name="list_customer"),
    path('edit_customer/<id_customer>', Edit_customer, name="edit_customer"),
    path('change_password', Change_password, name="change_password"),
    path('profile', Profile, name="profile"),
    path('list_project', List_project, name="list_project"),
    path('list_diary/<id_construction>', List_diary, name="list_diary"),
    path('show_diary/<id_diary>', Show_diary, name="show_diary"),
]

Diary/urls.py
from django.conf.urls import url
from django.urls import path
from Diary.views.construction.register_construction import Register_construction
from Diary.views.construction.show_construction_information import Show_construction_information
from Diary.views.construction.show_constructions import Show_constructions
from Diary.views.customer.edit_customer import Edit_customer
from Diary.views.customer.register_customer import Register_customer, autocompleteModel
from Diary.views.customer.show_customer import Show_customer
from Diary.views.diary.delete_contractor_equipment import Delete_contractor_equipment
from Diary.views.diary.delete_contractor_labor import Delete_contractor_labor
from Diary.views.diary.delete_diary import Delete_diary
from Diary.views.diary.delete_direct_labor import Delete_direct_labor
from Diary.views.diary.delete_equipment import Delete_equipment
from Diary.views.diary.delete_indirect_labor import Delete_indirect_labor
from Diary.views.diary.register_climate import Register_climate
from Diary.views.diary.register_contractor_equipment import Register_equipment_contractor
from Diary.views.diary.register_contractor_labor import Register_contractor_labor
from Diary.views.diary.register_diary import Register_diary
from Diary.views.diary.register_direct_labor import Register_direct_labor
from Diary.views.diary.register_equipment import Register_equipment
from Diary.views.diary.register_indirect_labor import Register_indirect_labor
from Diary.views.diary.register_observation import Register_observation
from Diary.views.diary.show_diary import Show_diary
from Diary.views.diary.show_diary_information import Show_diary_information
from Diary.views.diary.show_total_service import Show_total_service
from Diary.views.enginner.edit_customer import Edit_engineer
from Diary.views.enginner.enginner_register_customer import Enginner_register_customer
from Diary.views.enginner.register_engineer import Register_engineer
from Diary.views.enginner.show_customer import Show_engineer
from Diary.views.home.home_page import Index
from Diary.views.access.login import Login
from Diary.views.access.logout import Logout
from Diary.views.access.recover_password import Recover_Password
from Diary.views.user.access import Register_access
from Diary.views.user.customer_register_access import Customer_register_access
from Diary.views.user.delete_user import Delete_user

urlpatterns = [
    #Login
    path('home_page', Index, name='home_page'),
    path('', Login, name="login"),
    path('logout', Logout, name="logout"),
    #User
    path('register_access', Register_access, name="register_access"),
    path('recover_password', Recover_Password, name="recover_password"),
    path('customer_register_access', Customer_register_access, name="customer_register_access"),
    path('delete_user/<user_id>', Delete_user, name="delete_user"),
    #Customer
    path('register_customer', Register_customer, name="register_customer"),
    path('show_customer', Show_customer, name="show_customer"),
    path('edit_customer/<id_customer>', Edit_customer, name="edit_customer"),
    #Enginner
    path('register_engineer', Register_engineer, name="register_engineer"),
    path('show_engineer', Show_engineer, name="show_engineer"),
    path('edit_engineer', Edit_engineer, name="edit_engineer"),
    path('enginner_register_customer/<user>', Enginner_register_customer, name="enginner_register_customer"),
    #Construction
    path('register_construction', Register_construction, name="register_construction"),
    path('show_constructions', Show_constructions, name="show_constructions"),
    path('show_construction_information/<id_construction>', Show_construction_information, name="show_construction_information"),
    #Diary
    path('register_diary/<id_construction>', Register_diary, name="register_diary"),
    path('register_direct_labor/<diary>', Register_direct_labor, name="register_direct_labor"),
    path('register_indirect_labor/<diary>', Register_indirect_labor, name="register_indirect_labor"),
    path('register_equipment/<diary>', Register_equipment, name="register_equipment"),
    path('register_contractor_labor/<diary>', Register_contractor_labor, name="register_contractor_labor"),
    path('register_equipment_contractor/<diary>', Register_equipment_contractor, name="register_equipment_contractor"),
    path('register_climate/<diary>', Register_climate, name="register_climate"),
    path('register_observation/<diary>', Register_observation, name="register_observation"),

    path('delete_diary/<diary_id>', Delete_diary, name="delete_diary"),
    path('delete_direct_labor/<diary>/<direct_labor_id>', Delete_direct_labor, name="delete_direct_labor"),
    path('delete_indirect_labor/<diary>/<indirect_labor_id>', Delete_indirect_labor, name="delete_indirect_labor"),
    path('delete_contractor_labor/<diary>/<contractor_labor_id>', Delete_contractor_labor, name="delete_contractor_labor"),
    path('delete_equipment/<diary>/<equipment_id>', Delete_equipment, name="delete_equipment"),
    path('delete_equipment_contractor/<diary>/<equipment_contractor_id>', Delete_contractor_equipment, name="delete_equipment_contractor"),


    path('show_total_service/<diary>', Show_total_service, name="show_total_service"),
    path('show_diary', Show_diary, name="show_diary"),
    path('show_diary_information/<id_diary>', Show_diary_information, name="show_diary_information"),


    url(r'^ajax_calls/search/', autocompleteModel),
]

Customer/models.py
from django.db import models

# Create your models here.

Customer/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from Customer.forms.customer.register_customer_form import Customer_form
from Customer.services import customer_service
from Diary.forms.user.register_access_form import Access_form
from Diary.models import *


@login_required(login_url='login')
def Index(request):
    user = request.user
    user = Access.objects.get(id=user.id)

    customer = Customer.objects.get(user_access_id=user.id)
    engineer = Engineer.objects.get(id=customer.engineer.id)

    constructions = Construction.objects.filter(construction_company_customer_id=customer.id)

    return render(request, 'Customer/home/index.html', locals())


def autocompleteModel(request):
    if request.is_ajax():
        # pegando o nome digitado no post
        nome_customer = request.GET.get('term', '').capitalize()

        # pegando o objeto cujo nome é o digitado no post e usa o "startswith" para exibir
        customer = Engineer.objects.filter(engineer_name__icontains=nome_customer)

        resultado = []
        for r in customer:
            resultado.append(r.engineer_name)
        data = json.dumps(resultado)
    else:
        data = 'Falhou'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


@login_required(login_url='login')
def Register_customer(request):
    engineer = Engineer.objects.all()
    form_customer = Customer_form()
    user = request.user.id

    if request.method == 'POST':
        form_customer = Customer_form(data=request.POST)
        if form_customer.is_valid():
            user_access = form_customer.cleaned_data['user_access']
            engineer = form_customer.cleaned_data['engineer']
            customer_name = form_customer.cleaned_data['customer_name']
            customer_cnpj = form_customer.cleaned_data['customer_cnpj']
            customer_contact = form_customer.cleaned_data['customer_contact']
            customer_street = form_customer.cleaned_data['customer_street']
            customer_number = form_customer.cleaned_data['customer_number']
            customer_city = form_customer.cleaned_data['customer_city']
            customer_state = form_customer.cleaned_data['customer_state']
            customer_cod = form_customer.cleaned_data['customer_cod']

            customer = Customer(
                user_access=user_access,
                engineer=engineer,
                customer_name=customer_name,
                customer_cnpj=customer_cnpj,
                customer_contact=customer_contact,
                customer_street=customer_street,
                customer_number=customer_number,
                customer_city=customer_city,
                customer_state=customer_state,
                customer_cod=customer_cod,
            )

            customer_service.Register_customer(customer)

            return redirect('customer:index')
    else:
        form_customer = Customer_form()
    return render(request, 'Diary/customer/register_customer.html', locals())


@login_required(login_url='login')
def Edit_customer(request, id_customer):
    customer = Customer.objects.get(user_access_id=request.user.id)

    form = Customer_form(request.POST or None, instance=customer)
    if form.is_valid():
        form.save()
        return redirect('customer:profile')
    return render(request, 'Customer/customer/edit_customer.html', locals())


@login_required(login_url='login')
def List_customer(request):
    user = request.user

    customer = Customer.objects.get(user_access_id=user.id)
    return render(request, 'Customer/customer/list_customer.html', locals())


@login_required(login_url='login')
def Change_password(request):
    user = Access.objects.get(id=request.user.id)
    form = Access_form(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect('customer:index')
    return render(request, 'Customer/customer/change_password.html', locals())


@login_required(login_url='login')
def Profile(request):
    customer = Customer.objects.get(user_access_id=request.user.id)
    return render(request, 'Customer/home/profile.html', locals())


@login_required(login_url='login')
def List_project(request):
    user = request.user
    user = Access.objects.get(id=user.id)

    customer = Customer.objects.get(user_access_id=user.id)
    engineer = Engineer.objects.get(id=customer.engineer.id)

    constructions = Construction.objects.filter(construction_company_customer_id=customer.id)

    return render(request, 'Customer/home/list_project.html', locals())


@login_required(login_url='login')
def List_diary(request, id_construction):

    diary = Diary.objects.filter(diary_construction_id=id_construction)

    return render(request, 'Customer/home/list_diary.html', locals())


@login_required(login_url='login')
def Show_diary(request, id_diary):

    diary = Diary.objects.get(id=id_diary)
    direct_labor = Direct_labor.objects.filter(direct_labor_diary_id=id_diary)
    indirect_labor = Indirect_labor.objects.filter(indirect_labor_diary_id=id_diary)
    contractor_labor = Contractor_labor.objects.filter(contractor_labor_diary_id=id_diary)
    equipment_construction = Equipment_construction.objects.filter(equipment_construction_diary_id=id_diary)
    contractor_equipment = Contractor_equipment.objects.filter(contractor_equipment_diary_id=id_diary)
    climate = Climate.objects.get(climate_diary_id=id_diary)
    total_service = Total_service.objects.get(total_service_diary_id=id_diary)
    observation = Observation.objects.get(observation_diary_id=id_diary)
    
    return render(request, 'Customer/home/show_diary.html', locals())

templates/Customer/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link href="{% static 'diary/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'diary/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" crossorigin="anonymous" />
        <script src="{% static 'diary/js/all.min.js' %}" crossorigin="anonymous"></script>

        <title>{% block title %} {% endblock %}</title>
    </head>

    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'customer:index' %}">DIÁRIO DE OBRAS <i class="fa fa-car fa-2x" aria-hidden="true"></i>
            </a> <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>

            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0"></form>

            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Configuração</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
        </nav>

        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">

                    <div class="sb-sidenav-menu">
                        <div class="nav">
                              <div class="sb-sidenav-menu-heading">CONTROLES</div><hr>
                              <li class="nav-item">
                                <a class="nav-link" href="{% url 'customer:list_customer' %}">
                                  <!--<i class="fas fa-fw fas fa-user-edit"></i>-->
                                  <span>Perfil</span></a>
                              </li>
                              <li class="nav-item">
                                <a class="nav-link" href="#">
                                  <!--<i class="fas fa-fw fas fa-car"></i>-->
                                  <span>Relatórios</span></a>
                              </li>

                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                {% block conteudo %}

                <!-- conteúdo -->

                {% endblock %}
                    <!-- Rodapé -->
                <script src="//code.jivosite.com/widget/0tezDQaAxw" async></script>

                <footer class="bg-transparent mt-auto"><hr>
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2019</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>

        <script src="{% static 'diary/js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'diary/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'diary/js/scripts.js' %}"></script>
        <script src="{% static 'diary/js/Chart.min.js' %}"></script>
        <script src="{% static 'diary/js/chart-area-demo.js' %}"></script>
        <script src="{% static 'diary/js/chart-bar-demo.js'  %}"></script>
        <script src="{% static 'diary/js/jquery.dataTables.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'diary/js/dataTables.bootstrap4.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'diary/js/datatables-demo.js' %}"></script>
    </body>
</html>

templates/Customer/home/list_diary.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pagina principal</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'customer/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%  static 'customer/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Diário de Obras</a>
                <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'customer:index' %}">Início</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'logout' %}">Sair</a></li>
                    </ul>
                </div>
            </div>
        </nav><br>

         <!-- Contact Section-->
        <section class="page-section" id="contact">
            <div class="mt-10">
                <div class="container mt-5">
                    <!-- Contact Section Heading-->
                    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Diário</h2>
                    <!-- Icon Divider-->
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                    <!-- Contact Section Form-->
                    <div class="row">
                        <div class="col-lg-8 mx-auto">
                            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.-->
                            <table class="table">
                              <thead class="thead-dark">
                                <tr>
                                  <th scope="col">Número</th>
                                  <th scope="col">Data</th>
                                  <th scope="col">Relatório</th>
                                </tr>
                              </thead>
                                <tbody>
                                {% for i in diary %}
                                    <tr>
                                      <td>{{ i.id }}</td>
                                      <td>{{ i.diary_date_day }}</td>
                                      <td><a class="btn btn-primary mr-3" href="{% url 'customer:show_diary' i.id %}">Ver</a></td>
                                    </tr>
                                {% endfor %}
                              </tbody>
                            </table><hr>
                        <a class="btn btn-danger mr-3" href="{% url 'customer:list_project' %}">Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Endereço</h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br />
                            Clark, MO 65243
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Minhas redes sociais</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">Desenvolvedor</h4>
                        <p class="lead mb-0">
                            Todos os direitos resevados!
                            <br><a target="_blank" href="https://matheus-bertoldo.herokuapp.com/">Matheus Bertoldo</a>

                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright © Your Website 2020</small></div>
        </div>
        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
        <div class="scroll-to-top d-lg-none position-fixed">
            <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a>
        </div>


        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'customer/assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'customer/assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'customer/js/scripts.js' %}"></script>
    </body>
</html>

templates/Customer/home/teste.html
<form method="post">
                                  {% csrf_token %}
                                  <div class="form-row">
                                      <div class="form-group col-md-6">
                                        <label for="empClienteRazao" class="col-form-label" >Razão Social:</label>
                                        <input name="empClienteRazao" type="text" class="form-control" id="empClienteRazao" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.empClienteRazao }}">
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label for="empClienteCNPJ" class="col-form-label" >CNPJ:</label>
                                        <input name="empClienteCNPJ" type="text" class="form-control" id="empClienteCNPJ" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.empClienteCNPJ }}">
                                      </div>
                                  </div>

                                  <div class="form-row">
                                      <div class="form-group col-md-6">
                                        <label for="empClienteRespon" class="col-form-label" >Responsavel:</label>
                                        <input name="empClienteRespon" type="text" class="form-control" id="empClienteRespon" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.empClienteRespon }}">
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label for="empClienteContato" class="col-form-label" >Contato:</label>
                                        <input name="empClienteContato" type="text" class="form-control" id="empClienteContato" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.empClienteContato }}">
                                      </div>
                                  </div>

                                  <div class="form-row">
                                      <div class="form-group col-md-8">
                                        <label for="empClienteEmail" class="col-form-label" >Email:</label>
                                        <input name="empClienteEmail" type="email" class="form-control" id="empClienteEmail" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.empClienteEmail }}">
                                      </div>
                                      <div class="form-group col-md-4">
                                        <label for="endCEP" class="col-form-label" >CEP:</label>
                                        <input name="endCEP" type="text" class="form-control" id="endCEP" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.endCEP }}">
                                      </div>
                                  </div>

                                  <div class="form-row">
                                      <div class="form-group col-md-10">
                                        <label for="endRua" class="col-form-label" >Rua:</label>
                                        <input name="endRua" type="text" class="form-control" id="endRua" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.endRua }}">
                                      </div>
                                      <div class="form-group col-md-2">
                                        <label for="endNum" class="col-form-label" >Número:</label>
                                        <input name="endNum" type="number" class="form-control" id="endNum" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.endNum }}">
                                      </div>
                                  </div>

                                  <div class="form-row">
                                      <div class="form-group col-md-10">
                                        <label for="endCidade" class="col-form-label" >Cidade:</label>
                                        <input name="endCidade" type="text" class="form-control" id="endCidade" onkeyup="this.value=this.value.toUpperCase();" value="{{ cliente.endCidade }}">
                                      </div>
                                      <div class="form-group col-md-2">
                                          <label class="col-form-label" for="endEstado">Estado:</label>
                                          <select name="endEstado" id="endEstado"  class="form-control">
                                            <option selected>{{ cliente.endEstado }}</option>
                                            <option>AC</option>
                                            <option>AL</option>
                                            <option>AL</option>
                                            <option>AM</option>
                                            <option>BA</option>
                                            <option>CE</option>
                                            <option>DF</option>
                                            <option>ES</option>
                                            <option>GO</option>
                                            <option>MA</option>
                                            <option>MT</option>
                                            <option>MS</option>
                                            <option>MG</option>
                                            <option>PA</option>
                                            <option>PB</option>
                                            <option>PR</option>
                                            <option>PE</option>
                                            <option>PI</option>
                                            <option>RJ</option>
                                            <option>RN</option>
                                            <option>RS</option>
                                            <option>RO</option>
                                            <option></option>
                                            <option></option>
                                          </select>
                                      </div>
                                  </div>
                            <div class="card-body"><hr>
                                 <a class="btn btn-success mr-3" href="{% url 'register_direct_labor' %}">Cadastrar</a>
                                 <a class="btn btn-danger mr-3" href="{% url 'home_page' %}">Cancelar</a>
                            </div>
                        </form>