Construction/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Diary.urls')),
    path('customer/', include('Customer.urls', namespace='customer')),

]

Customer/urls.py
from django.urls import path

from Customer.views import *

app_name = 'customer'

urlpatterns = [
    path('index', Index, name='index'),
    path('register_customer', Register_customer, name='register_customer'),
    path('list_customer', List_customer, name="list_customer"),
    path('edit_customer/<id_customer>', Edit_customer, name="edit_customer"),
    path('change_password', Change_password, name="change_password"),
    path('profile', Profile, name="profile"),
    path('list_project', List_project, name="list_project"),
    path('list_diary/<id_construction>', List_diary, name="list_diary"),
    path('show_diary/<id_diary>', Show_diary, name="show_diary"),
]

Diary/urls.py
from django.conf.urls import url
from django.urls import path
from Diary.views.construction.register_construction import Register_construction
from Diary.views.construction.show_construction_information import Show_construction_information
from Diary.views.construction.show_constructions import Show_constructions
from Diary.views.customer.edit_customer import Edit_customer
from Diary.views.customer.register_customer import Register_customer, autocompleteModel
from Diary.views.customer.show_customer import Show_customer
from Diary.views.diary.delete_contractor_equipment import Delete_contractor_equipment
from Diary.views.diary.delete_contractor_labor import Delete_contractor_labor
from Diary.views.diary.delete_diary import Delete_diary
from Diary.views.diary.delete_direct_labor import Delete_direct_labor
from Diary.views.diary.delete_equipment import Delete_equipment
from Diary.views.diary.delete_indirect_labor import Delete_indirect_labor
from Diary.views.diary.register_climate import Register_climate
from Diary.views.diary.register_contractor_equipment import Register_equipment_contractor
from Diary.views.diary.register_contractor_labor import Register_contractor_labor
from Diary.views.diary.register_diary import Register_diary
from Diary.views.diary.register_direct_labor import Register_direct_labor
from Diary.views.diary.register_equipment import Register_equipment
from Diary.views.diary.register_indirect_labor import Register_indirect_labor
from Diary.views.diary.register_observation import Register_observation
from Diary.views.diary.show_diary import Show_diary
from Diary.views.diary.show_diary_information import Show_diary_information
from Diary.views.diary.show_total_service import Show_total_service
from Diary.views.enginner.edit_customer import Edit_engineer
from Diary.views.enginner.enginner_register_customer import Enginner_register_customer
from Diary.views.enginner.register_engineer import Register_engineer
from Diary.views.enginner.show_customer import Show_engineer
from Diary.views.home.home_page import Index
from Diary.views.access.login import Login
from Diary.views.access.logout import Logout
from Diary.views.access.recover_password import Recover_Password
from Diary.views.user.access import Register_access
from Diary.views.user.customer_register_access import Customer_register_access
from Diary.views.user.delete_user import Delete_user

urlpatterns = [
    #Login
    path('home_page', Index, name='home_page'),
    path('', Login, name="login"),
    path('logout', Logout, name="logout"),
    #User
    path('register_access', Register_access, name="register_access"),
    path('recover_password', Recover_Password, name="recover_password"),
    path('customer_register_access', Customer_register_access, name="customer_register_access"),
    path('delete_user/<user_id>', Delete_user, name="delete_user"),
    #Customer
    path('register_customer', Register_customer, name="register_customer"),
    path('show_customer', Show_customer, name="show_customer"),
    path('edit_customer/<id_customer>', Edit_customer, name="edit_customer"),
    #Enginner
    path('register_engineer', Register_engineer, name="register_engineer"),
    path('show_engineer', Show_engineer, name="show_engineer"),
    path('edit_engineer', Edit_engineer, name="edit_engineer"),
    path('enginner_register_customer/<user>', Enginner_register_customer, name="enginner_register_customer"),
    #Construction
    path('register_construction', Register_construction, name="register_construction"),
    path('show_constructions', Show_constructions, name="show_constructions"),
    path('show_construction_information/<id_construction>', Show_construction_information, name="show_construction_information"),
    #Diary
    path('register_diary/<id_construction>', Register_diary, name="register_diary"),
    path('register_direct_labor/<diary>', Register_direct_labor, name="register_direct_labor"),
    path('register_indirect_labor/<diary>', Register_indirect_labor, name="register_indirect_labor"),
    path('register_equipment/<diary>', Register_equipment, name="register_equipment"),
    path('register_contractor_labor/<diary>', Register_contractor_labor, name="register_contractor_labor"),
    path('register_equipment_contractor/<diary>', Register_equipment_contractor, name="register_equipment_contractor"),
    path('register_climate/<diary>', Register_climate, name="register_climate"),
    path('register_observation/<diary>', Register_observation, name="register_observation"),

    path('delete_diary/<diary_id>', Delete_diary, name="delete_diary"),
    path('delete_direct_labor/<diary>/<direct_labor_id>', Delete_direct_labor, name="delete_direct_labor"),
    path('delete_indirect_labor/<diary>/<indirect_labor_id>', Delete_indirect_labor, name="delete_indirect_labor"),
    path('delete_contractor_labor/<diary>/<contractor_labor_id>', Delete_contractor_labor, name="delete_contractor_labor"),
    path('delete_equipment/<diary>/<equipment_id>', Delete_equipment, name="delete_equipment"),
    path('delete_equipment_contractor/<diary>/<equipment_contractor_id>', Delete_contractor_equipment, name="delete_equipment_contractor"),


    path('show_total_service/<diary>', Show_total_service, name="show_total_service"),
    path('show_diary', Show_diary, name="show_diary"),
    path('show_diary_information/<id_diary>', Show_diary_information, name="show_diary_information"),


    url(r'^ajax_calls/search/', autocompleteModel),
]

Customer/models.py
from django.db import models

# Create your models here.

Customer/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from Customer.forms.customer.register_customer_form import Customer_form
from Customer.services import customer_service
from Diary.forms.user.register_access_form import Access_form
from Diary.models import *


@login_required(login_url='login')
def Index(request):
    user = request.user
    user = Access.objects.get(id=user.id)

    customer = Customer.objects.get(user_access_id=user.id)
    engineer = Engineer.objects.get(id=customer.engineer.id)

    constructions = Construction.objects.filter(construction_company_customer_id=customer.id)

    return render(request, 'Customer/home/index.html', locals())


def autocompleteModel(request):
    if request.is_ajax():
        # pegando o nome digitado no post
        nome_customer = request.GET.get('term', '').capitalize()

        # pegando o objeto cujo nome é o digitado no post e usa o "startswith" para exibir
        customer = Engineer.objects.filter(engineer_name__icontains=nome_customer)

        resultado = []
        for r in customer:
            resultado.append(r.engineer_name)
        data = json.dumps(resultado)
    else:
        data = 'Falhou'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


@login_required(login_url='login')
def Register_customer(request):
    engineer = Engineer.objects.all()
    form_customer = Customer_form()
    user = request.user.id

    if request.method == 'POST':
        form_customer = Customer_form(data=request.POST)
        if form_customer.is_valid():
            user_access = form_customer.cleaned_data['user_access']
            engineer = form_customer.cleaned_data['engineer']
            customer_name = form_customer.cleaned_data['customer_name']
            customer_cnpj = form_customer.cleaned_data['customer_cnpj']
            customer_contact = form_customer.cleaned_data['customer_contact']
            customer_street = form_customer.cleaned_data['customer_street']
            customer_number = form_customer.cleaned_data['customer_number']
            customer_city = form_customer.cleaned_data['customer_city']
            customer_state = form_customer.cleaned_data['customer_state']
            customer_cod = form_customer.cleaned_data['customer_cod']

            customer = Customer(
                user_access=user_access,
                engineer=engineer,
                customer_name=customer_name,
                customer_cnpj=customer_cnpj,
                customer_contact=customer_contact,
                customer_street=customer_street,
                customer_number=customer_number,
                customer_city=customer_city,
                customer_state=customer_state,
                customer_cod=customer_cod,
            )

            customer_service.Register_customer(customer)

            return redirect('customer:index')
    else:
        form_customer = Customer_form()
    return render(request, 'Diary/customer/register_customer.html', locals())


@login_required(login_url='login')
def Edit_customer(request, id_customer):
    customer = Customer.objects.get(user_access_id=request.user.id)

    form = Customer_form(request.POST or None, instance=customer)
    if form.is_valid():
        form.save()
        return redirect('customer:profile')
    return render(request, 'Customer/customer/edit_customer.html', locals())


@login_required(login_url='login')
def List_customer(request):
    user = request.user

    customer = Customer.objects.get(user_access_id=user.id)
    return render(request, 'Customer/customer/list_customer.html', locals())


@login_required(login_url='login')
def Change_password(request):
    user = Access.objects.get(id=request.user.id)
    form = Access_form(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect('customer:index')
    return render(request, 'Customer/customer/change_password.html', locals())


@login_required(login_url='login')
def Profile(request):
    customer = Customer.objects.get(user_access_id=request.user.id)
    return render(request, 'Customer/home/profile.html', locals())


@login_required(login_url='login')
def List_project(request):
    user = request.user
    user = Access.objects.get(id=user.id)

    customer = Customer.objects.get(user_access_id=user.id)
    engineer = Engineer.objects.get(id=customer.engineer.id)

    constructions = Construction.objects.filter(construction_company_customer_id=customer.id)

    return render(request, 'Customer/home/list_project.html', locals())


@login_required(login_url='login')
def List_diary(request, id_construction):

    diary = Diary.objects.filter(diary_construction_id=id_construction)

    return render(request, 'Customer/home/list_diary.html', locals())


@login_required(login_url='login')
def Show_diary(request, id_diary):

    diary = Diary.objects.get(id=id_diary)
    direct_labor = Direct_labor.objects.filter(direct_labor_diary_id=id_diary)
    indirect_labor = Indirect_labor.objects.filter(indirect_labor_diary_id=id_diary)
    contractor_labor = Contractor_labor.objects.filter(contractor_labor_diary_id=id_diary)
    equipment_construction = Equipment_construction.objects.filter(equipment_construction_diary_id=id_diary)
    contractor_equipment = Contractor_equipment.objects.filter(contractor_equipment_diary_id=id_diary)
    climate = Climate.objects.get(climate_diary_id=id_diary)
    total_service = Total_service.objects.get(total_service_diary_id=id_diary)
    observation = Observation.objects.get(observation_diary_id=id_diary)
    
    return render(request, 'Customer/home/show_diary.html', locals())

templates/Customer/customer/change_password.html
{% extends 'Customer/home/base.html' %}
{% load static %}
{% block title %}Editando Cliente{% endblock %}
{% block conteudo %}
                <main>
                    <div class="container-fluid">
                        <ol class="breadcrumb mb-auto">
                            <a class="breadcrumb-item active" href="{% url 'show_customer' %}">Clientes</a><li class="breadcrumb-item active">Cadastrar Obra</li>
                        </ol>

                        <form method="post">{% csrf_token %}
                            <div class="modal-body">

                              <div class="form-row">
                                    <div class="form-group col-md-6">
                                      <label class="col-form-label" for="customer_name">Nova senha</label>
                                      <input name="password1" type="password" id="customer_name" class="form-control" autocomplete="off" required="required">
                                      <input name="email" type="hidden" id="password1" value="{{ user.email }}">
                                      <input name="user_type" type="hidden" id="password1" value="{{ user.user_type }}">
                                      <input name="registration_mode" type="hidden" id="password1" value="2">
                                    </div>

                                    <div class="form-group col-md-6">
                                      <label class="col-form-label" for="password2">Confirmar senha</label>
                                      <input class="form-control" name="password2" type="password" id="password2" autocomplete="off" required="required">
                                    </div>
                              </div>
                            </div>
                            <div class="card-body"><hr>
                                 <button class="btn btn-success mr-3" type="submit">Salvar</button>
                                 <a class="btn btn-danger mr-3" href="{% url 'customer:list_customer' %}">Cancelar</a>
                            </div>
                        </form>
                    </div>
                </main>
{% endblock %}

templates/Customer/customer/customer_edit_customer.html
{% extends 'Customer/home/base.html' %}
{% load static %}
{% block title %}Editando Cliente{% endblock %}
{% block conteudo %}
                <main>
                    <div class="container-fluid">
                        <ol class="breadcrumb mb-auto">
                            <a class="breadcrumb-item active" href="{% url 'show_customer' %}">Clientes</a><li class="breadcrumb-item active">Cadastrar Obra</li>
                        </ol>

                        <form method="post">{% csrf_token %}
                            <div class="modal-body">

                              <div class="form-row">
                                    <div class="form-group col-md-5">
                                      <label class="col-form-label" for="customer_name">Nome</label>
                                      <input name="customer_name" type="text" id="customer_name" class="form-control" value="{{ customer.customer_name }}" required="required">
                                      <input name="user_access" type="hidden" value="{{ customer.user_access.id }}">
                                      <input name="engineer" type="hidden" id="engineer_name" value="{{ customer.engineer.id }}">
                                    </div>

                                    <div class="form-group col-md-4">
                                      <label class="col-form-label" for="customer_cnpj">CNPJ</label>
                                      <input name="customer_cnpj" type="hidden" id="customer_cnpj" value="{{ customer.customer_cnpj }}">
                                        <p id="customer_cnpj" class="form-control">{{ customer.customer_cnpj }}</p>
                                    </div>
                                    <div class="form-group col-md-3">
                                      <label class="col-form-label" for="customer_contact">Contato</label>
                                      <input name="customer_contact" type="text" id="customer_contact" class="form-control" value="{{ customer.customer_contact }}" required="required">
                                    </div>
                              </div>

                              <div class="form-row">
                                    <div class="form-group col-md-8">
                                      <label class="col-form-label" for="customer_street">Endereço</label>
                                      <input name="customer_street" type="text" id="customer_street" class="form-control" value="{{ customer.customer_street }}" required="required">
                                    </div>

                                    <div class="form-group col-md-4">
                                      <label class="col-form-label" for="customer_number">Número</label>
                                      <input name="customer_number" type="number" id="customer_number" class="form-control" value="{{ customer.customer_number }}" required="required">
                                    </div>
                              </div>

                              <div class="form-row">
                                    <div class="form-group col-md-6">
                                      <label class="col-form-label" for="customer_city">Cidade</label>
                                      <input name="customer_city" type="text" id="customer_city" class="form-control" value="{{ customer.customer_city }}" required="required">
                                    </div>

                                    <div class="form-group col-md-2">
                                      <label class="col-form-label" for="customer_state">Estado</label>
                                      <input name="customer_state" type="text" id="customer_state" class="form-control" value="{{ customer.customer_state }}" required="required">
                                    </div>

                                    <div class="form-group col-md-4">
                                      <label class="col-form-label" for="customer_cod">CEP</label>
                                      <input name="customer_cod" type="text" id="customer_cod" class="form-control" value="{{ customer.customer_cod }}" required="required">
                                    </div>
                              </div>
                            </div>
                            <div class="card-body"><hr>
                                 <button class="btn btn-success mr-3" type="submit">Editar</button>
                                 <a class="btn btn-danger mr-3" href="{% url 'show_customer' %}">Cancelar</a>
                            </div>
                        </form>
                    </div>
                </main>
{% endblock %}

templates/Customer/customer/list_customer.html
{% extends 'Customer/home/base.html' %}
{% load static %}
{% block title %}Editando Cliente{% endblock %}
{% block conteudo %}
                <main>
                    <div class="container-fluid">
                        <ol class="breadcrumb mb-auto">
                            <a class="breadcrumb-item active" href="{% url 'show_customer' %}">Clientes</a><li class="breadcrumb-item active">Cadastrar Obra</li>
                        </ol><br>

                        <form method="post">{% csrf_token %}
                            <div class="modal-body">

                              <div class="form-row">
                                    <div class="form-group col-md-5">
                                      <label class="col-form-label" for="customer_name">Nome</label>
                                      <p>{{ customer.customer_name }}</p><hr>
                                    </div>

                                    <div class="form-group col-md-4">
                                      <label class="col-form-label" for="customer_cnpj">CNPJ</label>
                                        <p>{{ customer.customer_cnpj }}</p><hr>
                                    </div>
                                    <div class="form-group col-md-3">
                                      <label class="col-form-label" for="customer_contact">Contato</label>
                                      <p>{{ customer.customer_contact }}</p><hr>
                                    </div>
                              </div>

                              <div class="form-row">
                                    <div class="form-group col-md-8">
                                      <label class="col-form-label" for="customer_street">Endereço</label>
                                      <p>{{ customer.customer_street }}</p><hr>
                                    </div>

                                    <div class="form-group col-md-4">
                                      <label class="col-form-label" for="customer_number">Número</label>
                                      <p>{{ customer.customer_number }}</p><hr>
                                    </div>
                              </div>

                              <div class="form-row">
                                    <div class="form-group col-md-6">
                                      <label class="col-form-label" for="customer_city">Cidade</label>
                                      <p>{{ customer.customer_city }}</p><hr>
                                    </div>

                                    <div class="form-group col-md-2">
                                      <label class="col-form-label" for="customer_state">Estado</label>
                                      <p>{{ customer.customer_state }}</p><hr>
                                    </div>

                                    <div class="form-group col-md-4">
                                      <label class="col-form-label" for="customer_cod">CEP</label>
                                      <p>{{ customer.customer_cod }}</p><hr>
                                    </div>
                              </div>
                            </div>
                            <div class="card-body"><hr>
                                 <a class="btn btn-success mr-3" href="{% url 'customer:edit_customer' customer.id %}">Editar</a>
                                 <a class="btn btn-primary mr-3" href="{% url 'customer:change_password' %}">Alterar senha</a>
                                 <a class="btn btn-danger mr-3" href="{% url 'customer:index' %}">Voltar</a>
                            </div>
                        </form>
                    </div>
                </main>
{% endblock %}

templates/Customer/customer/show_customer.html
{% extends 'Diary/home/base.html' %}
{% load static %}
{% block title %}Clientes{% endblock %}
                {% block conteudo %}
                <main>
                    <div class="container-fluid">
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Clientes</li>
                        </ol>
                        <div class="modal-body">
                            <table class="table table-hover table-dark">
                                  <thead>
                                    <tr>
                                      <th scope="col">Nome</th>
                                      <th scope="col">Ações</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                  {% for i in customers %}
                                    <tr>
                                      <th scope="row">{{ i }}</th>
                                      <td><a class="btn btn-info mr-3" href="{% url 'edit_customer' i.id %}">Editar</a></td>
                                    </tr>
                                  {% endfor %}
                                  </tbody>
                            </table>
                        </div>

                        <div class="card-body"><hr>
                            <a class="btn btn-success mr-3" href="{% url 'customer_register_access' %}">Cadastrar</a>
                        </div>
                    </div>
                </main>
                {% endblock %}